### ISSUE TITLE
Question: how do you obtain the 7 device constant UUID?

### ISSUE THREAD

**Issue by billyjoker** [ilteoood/bluetooth_piconet#1]
Hi i am not sure but i believe that these constants:

        uuidList.add(UUID.fromString("fe964a9c-184c-11e6-b6ba-3e1d05defe78"));
        uuidList.add(UUID.fromString("fe964e02-184c-11e6-b6ba-3e1d05defe78"));
        uuidList.add(UUID.fromString("fe964f9c-184c-11e6-b6ba-3e1d05defe78"));
        uuidList.add(UUID.fromString("fe965438-184c-11e6-b6ba-3e1d05defe78"));
        uuidList.add(UUID.fromString("fe9655be-184c-11e6-b6ba-3e1d05defe78"));
        uuidList.add(UUID.fromString("fe965708-184c-11e6-b6ba-3e1d05defe78"));
        uuidList.add(UUID.fromString("fe965848-184c-11e6-b6ba-3e1d05defe78"));

They are random strings? Is there any criteria to generate them? I am working with 5 Adafruit BLE devices and my android mobile phone trying to connect to them..
Many thanks.

**Comment by ilteoood** [comment]
Hi @billyjoker,
yes they are just random strings. There is a criteria to generate them, and I suggest you to read this article:
https://www.baeldung.com/java-uuid

Regards,
Matteo
